[package]
name = "cloud_object_models"
version = "0.1.0"
edition = "2024"
authors.workspace = true
publish.workspace = true
license.workspace = true

[features]
test-util = ["cloud_objects/test-util"]

[dependencies]
anyhow.workspace = true
chrono.workspace = true
log.workspace = true
cloud_objects.workspace = true
serde.workspace = true
serde_json.workspace = true
session-sharing-protocol.workspace = true
settings.workspace = true
uuid.workspace = true
warp-workflows.workspace = true
warp_core.workspace = true
warp_graphql.workspace = true
warp_util.workspace = true
warp_cli.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
cloud_object_persistence.workspace = true
diesel = { workspace = true, features = ["sqlite", "chrono"] }
persistence.workspace = true

[dev-dependencies]
cloud_objects = { workspace = true, features = ["test-util"] }
